env_name=atari-alien override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-amidar override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-assault override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-asterix override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-asteroids override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-atlantis override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-bank_heist override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-battle_zone override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-beam_rider override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-berzerk override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-bowling override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-boxing override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-breakout override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-centipede override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-chopper_command override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-crazy_climber override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-demon_attack override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-double_dunk override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-enduro override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-fishing_derby override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-freeway override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-frostbite override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-gopher override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-gravitar override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-hero override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-ice_hockey override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-jamesbond override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-kangaroo override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-krull override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-kung_fu_master override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-montezuma_revenge override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-ms_pacman override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-name_this_game override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-phoenix override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-pitfall override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-pong override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-private_eye override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-qbert override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-riverraid override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-road_runner override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-robotank override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-seaquest override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-skiing override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-solaris override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-space_invaders override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-star_gunner override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-tennis override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-time_pilot override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-tutankham override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-up_n_down override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-venture override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-video_pinball override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-wizard_of_wor override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-yars_revenge override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last
env_name=atari-zaxxon override_config='{}' run_name=run_1 python3 main.py -c configs/PPO/ppo.py --load_last